{'normalize_stats': False, 'use distilbert': True, 'use deberta': False, 'use mdeberta': True, 'use tw-roberta': False, 'use xlnet': True, 'use chars': True, 'use uppercased': True, 'use emojis': True, 'use posts': True, 'use duplicates': True, 'use word_nonwords': False, 'use nonword_words': True, 'use nonword_spaces': True, 'use space_punctuations': False, 'use hashtags': True, 'use urls': False, 'use mentions': True, 'enc_layers': 5, 'enc_power_layer_0': 8, 'enc_power_layer_1': 7, 'enc_power_layer_2': 12, 'enc_power_layer_3': 12, 'enc_power_layer_4': 7, 'enc_dropout': 0.7597946309871196, 'mbti_layers': 1, 'bigfive_c_layers': 1, 'bigfive_s_layers': 1, 'mbti_power_layer_0': 9, 'bigfive_c_power_layer_0': 4, 'bigfive_s_power_layer_0': 4, 'mbti_dropout': 0.06732066673384166, 'bigfive_c_dropout': 0.11481148455379332, 'bigfive_s_dropout': 0.38077827200018854, 'weighting': 'MGDA', 'architecture': 'DSelect_k', 'mtl_lr': 0.00976160426607926, 'mtl_weight_decay': 0.014905550815763176, 'mtl_step_size': 15, 'mtl_gamma': 0.0013633976642375332, 'mtl_patience': 22} because of the following error: RuntimeError('CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n').
